---

- name: user | genpw | create random password
  tags:
  - password
  set_fact:
    user_pw: "{{ lookup('password', '/dev/null') }}"

- name: user | genpw | host_vars dir
  tags:
  - directory
  become: false
  local_action:
    module: file
    path: "{{ pw_dir }}/{{ inventory_hostname }}"
    state: directory

- name: user | genpw | save password in host_vars
  tags:
  - hostvars
  become: false
  local_action:
    module: template
    src: pw.yml.j2
    dest: "{{ pw_dir }}/{{ inventory_hostname }}/pw.yml"
    mode: 0640
