---

- include_tasks: genpw.yml
  when: user_pw is not defined

- name: user | regular user
  user:
    name: "{{ user_name }}"
    password: "{{ user_pw | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}
    groups: "adm"
    shell: /bin/bash

- name: sudo | lock root account
  user:
    name: root
    password: "!"

- name: sudo | SSH keys
  tags:
  - ssh
  authorized_key:
    user: "{{ sudo_user }}"
    key: "{{ ssh_authorized_keys }}"
    exclusive: yes

