---

- include_tasks: genpw.yml
  when: user_pw is not defined

- name: user | regular user
  user:
    name: "{{ user_name }}"
    password: "{{ user_pw | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
    groups: "adm"
    append: yes
    shell: /bin/bash

- name: user | SSH keys
  tags:
  - ssh
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ ssh_authorized_keys }}"
    exclusive: yes

